// <auto-generated />
using System;
using DemirorenProject.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemirorenProject.API.Migrations
{
    [DbContext(typeof(NewsContext))]
    [Migration("20230728155449_DATABASECREATİON")]
    partial class DATABASECREATİON
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("DemirorenProject.API.Entities.CategoriesEN", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "sports"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "science"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "politics"
                        });
                });

            modelBuilder.Entity("DemirorenProject.API.Entities.NewsEN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = "This is the content for sports news",
                            Date = new DateTime(2023, 7, 28, 18, 54, 49, 502, DateTimeKind.Local).AddTicks(1389),
                            Title = "Test"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Content = "This is the content for science news",
                            Date = new DateTime(2023, 7, 28, 18, 54, 49, 502, DateTimeKind.Local).AddTicks(1402),
                            Title = "Test2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Content = "This is the content for politics news",
                            Date = new DateTime(2023, 7, 28, 18, 54, 49, 502, DateTimeKind.Local).AddTicks(1402),
                            Title = "Test3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Content = "This is the content for another politics news",
                            Date = new DateTime(2023, 7, 28, 18, 54, 49, 502, DateTimeKind.Local).AddTicks(1404),
                            Title = "Test4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
